### ISSUE TITLE
groupAll Performance

### ISSUE THREAD

**Issue by JackStouffer** [esjewett/reductio#12]
From https://github.com/square/crossfilter/issues/100

I added a column in the data via js with date.toDateSting() to test your theory. Here is the changed code.

```
var testDim = cs_data.dimension(function(d) {return d.DateString;});
var test_shipments = testDim.group().reduceSum(dc.pluck('DollarValue'));

reducer = reductio().groupAll(function(record) {
    var idx = mapped_date_array.indexOf(record.DateString);

    if (record.ShipDate < date_array[30]) {
        return [mapped_date_array[idx]];
    } else {
        var i = 0;
        var return_array = [];
                    
        // we are finding the 30 day moving avg 
        for (i = 30; i >= 0; i--) {
              if (typeof(mapped_date_array[idx - i]) != "undefined") {
                   return_array.push(mapped_date_array[idx - i]);
              }
        }

        return return_array;
    }
}).count(true).sum(function(d) { return d.DollarValue; }).avg(true);
```

and ran

```
console.time("values");
shipments_moving_avg.value();
console.timeEnd("values");
```

to test.

This yielded "values: 9869.228ms"

**Comment by esjewett** [comment]
Not sure if you're able to share a working example here? That would be awesome as I could track down the actual issue.

Also, I'm actually very surprised that calling .value() is taking so long. Maybe I'm misunderstanding something about how crossfilter.groupAll operates, but I didn't think it was doing any calculation, just returning a copy of the internal array. Maybe it's the copy that's taking a long time, but if so, I'd like to figure out why.

**Comment by JackStouffer** [comment]
Ok, it will take a second create a fake counter part to the actual data, as I am working with company records.

**Comment by esjewett** [comment]
Brilliant - thanks. If you can throw it all in plunkr, we can get down to business and try to make this fast.

**Comment by JackStouffer** [comment]
plunkr doesn't work with the large csv that I created. I doubt any others will either.

**Comment by esjewett** [comment]
Feel free to email it to me. https://github.com/esjewett

**Comment by JackStouffer** [comment]
This data is a lot less varied then the real data, so the speed might be a bit faster.

here is the code: https://gist.github.com/bac1725106f7194c41a1.git
here is the data: https://www.dropbox.com/s/h193t73aslnql97/dataJan-29-2015.csv

Let me know if you need anything else

**Comment by esjewett** [comment]
Ok, thanks for the example. I'm working on this a bit. I believe the issue is mostly going to be the efficiency of the function passed to groupAll, but I'm verifying that and will give you a more optimized version of a much simplified version of this gist once I've worked through it.

**Comment by esjewett** [comment]
Try this gist: https://gist.github.com/esjewett/8291936a4e4054342ba4

It's about 3x faster than the initial approach in my tests, taking about 5 seconds on my machine for the initial ```shipments_moving_avg.value()``` vs. 15-25 for different variations of the initial approach. I put in some comments regarding the performance and date-handling tricks I'm using. They are applicable to all Crossfilter applications, not just this one.

![screen shot 2015-01-29 at 8 34 55 pm](https://cloud.githubusercontent.com/assets/4822/5970265/5ada2562-a7f6-11e4-8f4e-a768e95f0a64.png)

Keep in mind that a 30-day moving average requires aggregating 30x the number of records because each record is placed in 30 groups and run through the reducers for each of those groups to aggregate it. So it's as if your data set actually has over 3 million records in it.

If you slowly add back your other dimensions while keeping an eye on the performance, you should be in OK shape to do interactive data analysis with this data set using Crossfilter and Reductio. There may be a few seconds lag for the big chunky filters (like if you filter by country), but dragging on timelines and such should work pretty interactively.

I'll try to keep using this data as a test-case for performance, but I think at this point further performance improvements may be marginal.

**Comment by esjewett** [comment]
Actually, looked at the profiler again and thought about it a bit more and realized we can move the Date object creation out of the loop. Cut off another ~40% and it's down to 3 seconds to aggregate the whole thing on my machine. Same gist.

**Comment by JackStouffer** [comment]
This works great, thanks. I'll close this issue now.

**Comment by esjewett** [comment]
There should be another performance speedup with the 0.5.1 version as we optimized the groupAll calculation loop internal to Reductio thanks to suggestions from @tannerlinsley.
