### ISSUE TITLE
Better instruction on how to avoid `VALUELIST accessor is being overwritten by max aggregation`

### ISSUE THREAD

**Issue by r4j4h** [esjewett/reductio#4]
I was curious about a good kitchen sink test of reductio on my data, and so I kept incrementally growing my calls on it and checking the data.

Everything behaves as expected, but I noticed these warnings pop up:

```
reductio.js:67 VALUELIST accessor is being overwritten by max aggregation
reductio.js:51 VALUELIST accessor is being overwritten by median aggregation
```

Here's a test case to demonstrate how easy it is the run into this:

```
var data = [
    {date: "2011-11-14T16:17:54Z", quantity: 2, total: 190, tip: 100, type: "tab"},
    {date: "2011-11-14T16:20:19Z", quantity: 2, total: 190, tip: 100, type: "tab"},
    {date: "2011-11-14T16:28:54Z", quantity: 1, total: 300, tip: 200, type: "visa"},
    {date: "2011-11-14T16:30:43Z", quantity: 2, total: 90, tip: 0, type: "tab"},
    {date: "2011-11-14T16:48:46Z", quantity: 2, total: 90, tip: 0, type: "tab"},
    {date: "2011-11-14T16:53:41Z", quantity: 2, total: 90, tip: 0, type: "tab"},
    {date: "2011-11-14T16:54:06Z", quantity: 1, total: 100, tip: 0, type: "cash"},
    {date: "2011-11-14T16:58:03Z", quantity: 2, total: 90, tip: 0, type: "tab"},
    {date: "2011-11-14T17:07:21Z", quantity: 2, total: 90, tip: 0, type: "tab"},
    {date: "2011-11-14T17:22:59Z", quantity: 2, total: 90, tip: 0, type: "tab"},
    {date: "2011-11-14T17:25:45Z", quantity: 2, total: 200, tip: 0, type: "cash"},
    {date: "2011-11-14T17:29:52Z", quantity: 1, total: 200, tip: 100, type: "visa"}
];

    var preparedData = $.map(data, function(datum, idx) {
        datum.date = moment(datum.date ).toDate();
        return datum;
    });

    // Prepare data, dimensions, and groups
    var sharedDx = crossfilter(preparedData);

    var dateDimForReductio = sharedDx.dimension(function (d) {
        var momentedDate = moment( d.date );
        return momentedDate.year() + '-' + momentedDate.month() + '-' + momentedDate.hour();
    });
    var groupForReductio = dateDimForReductio.group();

    var totalsAccessor = function() { return function(d) {
        return d.total;
    }; };

    var reducer = reductio();
    reducer
        .min(totalsAccessor())
        .median(totalsAccessor() )
    ;

    reducer(groupForReductio);
```

I think that the warnings are unavoidable with how the source is written. Is that intentional, or is there a better way of accomplishing this I am not seeing?

Here are the alternatives I have been able to imagine so far:

- Using several different reducers or the same reducer with separate `value` function sets. This definitely works, but leaves me wondering about performance -- is that causing multiple iterations through the dataset when only one is necessary, with both steps being performaned each tick? I would like to be as performant as possible, within reason. I can figure this out, but have not spent the time debugging things yet, and am hoping someone can illuminate this without me having to go to that extent.

- If `valueList` were an object, and each reducio function put its own valueLists under a key with that reducio function's name as the key, then they could co-exist in the same reductio-ized group. Then it would look like `value.valueList.min` next to `value.valueList.max`.

- If the `valueList` was compared against the proposed one, so that if they are identical no warning is thrown. This would have its own performance costs, every call. I point this out because the `valueList` from both `min` and `max` and `median` seem to be identical.. so the warning is harmless.

- A boolean flag could be added to disable the warning. This way when we have seen the warning and understand the complications, we can explicitly dismiss it from appearing.

I am hoping there's just something silly I'm missing that someone can point me to, or that some of this might help improve reductio. :) :+1:  to this library!!

**Comment by esjewett** [comment]
Yup, that's definitely suboptimal. As long as you pass in the same accessor to min and median you won't run in to any trouble, but if the accessor is different, that's going to be a problem. So you're approach is fine except for the warnings. For performance reasons I don't want to support separate accessors for each calculation, because the use case will usually be much like your own: min, median, and max on the same value. In this case we only want to maintain one value-list for the grouping.

If you want to have these calculations on separate values in a single group, you can use the new value() option in 0.0.5. It sounds like you've already landed on this as an option. This will maintain a separate value-list on each group for each "value" you define. Within that value, min, median, and max will still share a value-list. The performance should scale relatively linearly with the number of "value"s you define, but we *are* maintaining an array in each group with one element for every row in the group for each "value", so it's not going to scale without limit.

So, back to the original issue: the warning messages. I'm thinking of changing the API in one of the following ways:

 1. Just get rid of the warnings. They certainly shouldn't be popping up in production apps. I've seen some apps temporarily override the global console variable to control error messages, but that's pretty yucky.
 1. I can make the min, median, and max accessors take either a function or a boolean. Could then do ```
reducer.min(totalsAccessor()).median(true);``` without triggering the warning.

Would the 2nd option work for you? I'd prefer that because it will still throw the warnings when people wander into this potentially problematic situation.

**Comment by esjewett** [comment]
Just implemented the 2nd option above in the master branch. I will cut another release (0.0.6) that includes this as the nesting functionality soon, I hope.

**Comment by esjewett** [comment]
Published 0.0.6 on Bower and NPM. Please try it out if you have the chance! Going to close this issue for now.

**Comment by r4j4h** [comment]
Sorry for dropping off the face of the earth on you, that solution is great! Thank you very much. =)

**Comment by esjewett** [comment]
No worries, I do it all the time as well - thanks so much for the feedback!

**Comment by r4j4h** [comment]
Yeah, it's all too easy to do unfortunately. You are welcome and I hope I can contribute more in the future =D
